include:
  - project: cencosud-ds/cencommerce/utils/pipe-templates
    ref: master
    file: deploy-to-k8s.yml
stages:
  - init
  - test
  - apm
  - check
  - build
  - package
  - sast
  - validate-jira
  - deploy
  - dast
  - compliance-jira
  - result-security

.install_dependencies: &install_dependencies
  stage: init
  image: registry.gitlab.com/cencosud-ds/cencommerce/utils/docker-images/node:lts-alpine3.12
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 30 minutes
  tags:
    - private
    - ccom
    - staging

.lint: &lint
  stage: test
  image: registry.gitlab.com/cencosud-ds/cencommerce/utils/docker-images/node:lts-alpine3.12
  script:
    - npm run lint
  tags:
    - private
    - ccom
    - staging

.unit_test: &unit_test
  stage: test
  image: registry.gitlab.com/cencosud-ds/cencommerce/utils/docker-images/node:lts-alpine3.12
  script:
    - npm run test
  artifacts:
    paths:
      - coverage/
    expire_in: 30 minutes
  tags:
    - private
    - ccom
    - staging

######JOB: INSTALLL
install dependencies:
  <<: *install_dependencies

######JOB: Linter
linter:
  <<: *lint
  dependencies:
    - install dependencies
######JOB: UT
unit test:
  <<: *unit_test
  dependencies:
    - install dependencies
