version: '3.7'
services:
  node:
    env_file:
      - /app/secrets/ripley-api-user/app.local.env
    build:
      context: ./
      target: development
    image: nodejs-12:12.13.0-alpine
    working_dir: /app
    command: yarn run start:dev:full
    restart: always
    networks:
      - web
    volumes:
      - ./:/app
      - /app/secrets/dot_aws:/root/.aws
      - /app/secrets/dot_ssh:/root/.ssh
    ports:
      - "3108:3000"
      - "9113:9229"
    labels:
      - "traefik.port=4000"
      - "traefik.backend=ripley-api-user"
      - "traefik.frontend.rule=PathPrefixStrip:/api/user"

networks:
  web:
    external:
      name: ripley-sellercenter-platform_webgateway
