version: '3.6'
services:
  node:
    env_file:
    - .env
    build:
      context: ./
      target: development
    image: nodejs-12:12.13.0-alpine
    working_dir: /app
    command: yarn run start:dev:full
    restart: always
    networks:
      - web
    volumes:
      - ./:/app
    ports:
      - "3108:3000"

networks:
  web:
