version: '4.3'
services:
  node:
    env_file:
    - .env
    build:
      context: ./
      target: development
    image: walmart-challenge-backend-nodejs-12:12.13.0-alpine
    working_dir: /app
    command: yarn run start:dev
    restart: always
    networks:
      - web
    volumes:
      - ./:/app
    ports:
      - "3108:3000"
      - "9108:9229"

networks:
  web:
    external:
      name: walmart-challenge-backend-webgateway
